require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MeetingsController do

  let(:meeting) { FactoryGirl.create :meeting }

  describe "GET index" do
    context "when no year is passed" do
      it "gets all meetings from the current year" do
        Meeting.should_receive(:from_year).with(DateTime.now.year)
        get :index
      end

    it "gets all visible meetings" do
        Meeting.should_receive(:visible).and_return(mock.as_null_object)
        get :index
      end
    end

    context "when a year is passed" do
      it "gets all meetings from the current year" do
        Meeting.should_receive(:from_year).with(2012)
        get :index, :ano => "2012"
      end
    end

    it "assigns meetings from current year as @meetings" do
      Meeting.stub(:from_year).and_return([meeting])
      get :index
      assigns(:meetings).should == [meeting]
      response.should be_success
    end
  end

  describe "GET show" do
    it "assigns the requested meeting as @meeting" do
      get :show, :id => meeting.id
      assigns(:meeting).should == meeting
      response.should be_success
    end
  end
end

