require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MeetingsController do

  let(:meeting) { FactoryGirl.create :meeting }

  describe "GET index" do
    it "assigns all meetings as @meetings" do
      get :index
      assigns(:meetings).should == [meeting]
      response.should be_success
    end
  end

  describe "GET show" do
    it "assigns the requested meeting as @meeting" do
      get :show, :id => meeting.id
      assigns(:meeting).should == meeting
      response.should be_success
    end
  end
end

